import { Router, Response } from 'express';
import PDFDocument from 'pdfkit';
import { db } from '../db.ts';
import { requireAuth, AuthenticatedRequest } from '../auth.ts';

export const reportsRouter = Router();

// GET /api/reports/overview
reportsRouter.get('/overview', requireAuth, (req: AuthenticatedRequest, res: Response) => {
  const currentUser = req.user!;
  db.recalculateAllProjectProgress();
  const overview = db.getReportsOverview({ id: currentUser.id, role: currentUser.role });
  return res.json(overview);
});

// GET /api/reports/workload
reportsRouter.get('/workload', requireAuth, (req: AuthenticatedRequest, res: Response) => {
  const workload = db.getAllTeamMembersWorkload();
  return res.json(workload);
});

// Helper for CSV escaping
function escapeCsv(val: unknown): string {
  if (val === null || val === undefined) return '';
  const str = String(val);
  if (str.includes(',') || str.includes('"') || str.includes('\n') || str.includes('\r')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

// GET /api/reports/export/csv
reportsRouter.get('/export/csv', requireAuth, (req: AuthenticatedRequest, res: Response) => {
  try {
    const currentUser = req.user!;
    db.recalculateAllProjectProgress();
    const overview = db.getReportsOverview({ id: currentUser.id, role: currentUser.role });
    const workload = db.getAllTeamMembersWorkload();
    const attendance = db.getAttendanceStats();

    const lines: string[] = [];

    // Header & metadata
    lines.push('PLANFORGE ENTERPRISE OPERATIONS & ANALYTICS REPORT');
    lines.push(`Generated Date,${escapeCsv(new Date().toISOString())}`);
    lines.push(`Generated By,${escapeCsv(currentUser.name)} (${escapeCsv(currentUser.email)}) - ${escapeCsv(currentUser.role)}`);
    lines.push('');

    // 1. Project Status Breakdown
    lines.push('=== PROJECT STATUS BREAKDOWN ===');
    lines.push('Metric,Count / Percentage');
    lines.push(`Total Projects,${overview.projectMetrics.total}`);
    lines.push(`Active Projects,${overview.projectMetrics.active}`);
    lines.push(`Completed Projects,${overview.projectMetrics.completed}`);
    lines.push(`On Hold Projects,${overview.projectMetrics.onHold}`);
    lines.push(`Planning Projects,${overview.projectMetrics.planning}`);
    lines.push(`Average Project Progress,${overview.projectMetrics.averageProgress}%`);
    lines.push(`Low Priority Projects,${overview.projectMetrics.byPriority.LOW}`);
    lines.push(`Medium Priority Projects,${overview.projectMetrics.byPriority.MEDIUM}`);
    lines.push(`High Priority Projects,${overview.projectMetrics.byPriority.HIGH}`);
    lines.push(`Urgent Priority Projects,${overview.projectMetrics.byPriority.URGENT}`);
    lines.push('');

    // 2. Task Status Breakdown
    lines.push('=== TASK STATUS BREAKDOWN ===');
    lines.push('Task Metric / Priority,Count');
    lines.push(`Total Tasks,${overview.taskMetrics.total}`);
    lines.push(`To Do,${overview.taskMetrics.todo}`);
    lines.push(`In Progress,${overview.taskMetrics.inProgress}`);
    lines.push(`In Review,${overview.taskMetrics.review}`);
    lines.push(`Completed,${overview.taskMetrics.completed}`);
    lines.push(`Overdue Tasks,${overview.taskMetrics.overdue}`);
    lines.push(`Completion Rate,${overview.taskMetrics.completionRate}%`);
    lines.push(`Low Priority Tasks,${overview.taskMetrics.byPriority.LOW}`);
    lines.push(`Medium Priority Tasks,${overview.taskMetrics.byPriority.MEDIUM}`);
    lines.push(`High Priority Tasks,${overview.taskMetrics.byPriority.HIGH}`);
    lines.push(`Urgent Priority Tasks,${overview.taskMetrics.byPriority.URGENT}`);
    lines.push('');

    // 3. Attendance Summary
    lines.push('=== ATTENDANCE SUMMARY (TODAY) ===');
    lines.push('Metric,Value');
    lines.push(`Date,${escapeCsv(attendance.today)}`);
    lines.push(`Total Team Members,${attendance.totalTeamMembers}`);
    lines.push(`Present Today,${attendance.presentToday}`);
    lines.push(`Absent Today,${attendance.absentToday}`);
    lines.push(`Currently Working,${attendance.currentlyWorking}`);
    lines.push(`Currently on Break,${attendance.onBreak}`);
    lines.push(`Late Today,${attendance.lateToday}`);
    lines.push(`Half Day Today,${attendance.halfDayToday}`);
    lines.push(`On Leave Today,${attendance.onLeaveToday}`);
    lines.push(`Average Working Hours,${attendance.avgWorkingHours} hrs`);
    lines.push('');

    // 4. Team Workload
    lines.push('=== TEAM WORKLOAD ===');
    lines.push('Team Member,Email,Role,Assigned Projects,Active Tasks,Completed Tasks,Total Tasks,Workload Level,Attendance Status');
    for (const member of workload) {
      lines.push([
        escapeCsv(member.user.name),
        escapeCsv(member.user.email),
        escapeCsv(member.user.role),
        member.assignedProjectCount,
        member.activeTasksCount,
        member.completedTasksCount,
        member.totalTasksCount,
        escapeCsv(member.workloadLevel),
        escapeCsv(member.todayAttendanceStatus),
      ].join(','));
    }

    const csvContent = lines.join('\r\n');
    const filename = `planforge-report-${new Date().toISOString().split('T')[0]}.csv`;

    res.setHeader('Content-Type', 'text/csv; charset=utf-8');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    return res.status(200).send(csvContent);
  } catch (error: any) {
    console.error('Error generating CSV report:', error);
    return res.status(500).json({ message: 'Failed to generate CSV report', error: error.message });
  }
});

// GET /api/reports/export/pdf
reportsRouter.get('/export/pdf', requireAuth, (req: AuthenticatedRequest, res: Response) => {
  try {
    const currentUser = req.user!;
    db.recalculateAllProjectProgress();
    const overview = db.getReportsOverview({ id: currentUser.id, role: currentUser.role });
    const workload = db.getAllTeamMembersWorkload();
    const attendance = db.getAttendanceStats();

    const filename = `planforge-report-${new Date().toISOString().split('T')[0]}.pdf`;
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);

    const doc = new PDFDocument({
      size: 'A4',
      margin: 40,
      info: {
        Title: 'PlanForge Operations & Analytics Report',
        Author: 'PlanForge Platform',
      },
    });

    doc.pipe(res);

    // Primary Header
    doc.rect(40, 40, 515, 50).fill('#4F46E5');
    doc.fillColor('#FFFFFF').fontSize(18).text('PlanForge Operations & Analytics Report', 55, 50);
    doc.fontSize(9).fillColor('#E0E7FF').text(`Generated: ${new Date().toLocaleString()} | User: ${currentUser.name} (${currentUser.role})`, 55, 72);

    let y = 105;

    // Helper section header
    const drawSectionHeader = (title: string) => {
      if (y > 700) {
        doc.addPage();
        y = 40;
      }
      doc.rect(40, y, 515, 20).fill('#F3F4F6');
      doc.fillColor('#1F2937').fontSize(10).text(title, 48, y + 5);
      y += 28;
    };

    // Helper metric row
    const drawMetricRow = (label: string, value: string | number, col: number = 0) => {
      const x = col === 0 ? 50 : 310;
      doc.fillColor('#6B7280').fontSize(9).text(label, x, y);
      doc.fillColor('#111827').fontSize(9).text(String(value), x + 140, y, { align: 'left' });
    };

    // 1. Project Status Breakdown
    drawSectionHeader('1. Project Status Breakdown');
    drawMetricRow('Total Projects:', overview.projectMetrics.total, 0);
    drawMetricRow('Active Projects:', overview.projectMetrics.active, 1);
    y += 15;
    drawMetricRow('Completed Projects:', overview.projectMetrics.completed, 0);
    drawMetricRow('Planning Projects:', overview.projectMetrics.planning, 1);
    y += 15;
    drawMetricRow('On Hold Projects:', overview.projectMetrics.onHold, 0);
    drawMetricRow('Average Progress:', `${overview.projectMetrics.averageProgress}%`, 1);
    y += 15;
    drawMetricRow('Urgent Priority:', overview.projectMetrics.byPriority.URGENT, 0);
    drawMetricRow('High Priority:', overview.projectMetrics.byPriority.HIGH, 1);
    y += 24;

    // 2. Task Status Breakdown
    drawSectionHeader('2. Task Status & Execution');
    drawMetricRow('Total Tasks:', overview.taskMetrics.total, 0);
    drawMetricRow('In Progress Tasks:', overview.taskMetrics.inProgress, 1);
    y += 15;
    drawMetricRow('To Do Tasks:', overview.taskMetrics.todo, 0);
    drawMetricRow('Review Tasks:', overview.taskMetrics.review, 1);
    y += 15;
    drawMetricRow('Completed Tasks:', overview.taskMetrics.completed, 0);
    drawMetricRow('Overdue Tasks:', overview.taskMetrics.overdue, 1);
    y += 15;
    drawMetricRow('Completion Rate:', `${overview.taskMetrics.completionRate}%`, 0);
    drawMetricRow('Urgent Tasks:', overview.taskMetrics.byPriority.URGENT, 1);
    y += 24;

    // 3. Attendance Summary
    drawSectionHeader('3. Team Attendance Summary (Today)');
    drawMetricRow('Total Team Size:', attendance.totalTeamMembers, 0);
    drawMetricRow('Present Today:', attendance.presentToday, 1);
    y += 15;
    drawMetricRow('Currently Working:', attendance.currentlyWorking, 0);
    drawMetricRow('Currently on Break:', attendance.onBreak, 1);
    y += 15;
    drawMetricRow('Late Arrivals:', attendance.lateToday, 0);
    drawMetricRow('On Leave Today:', attendance.onLeaveToday, 1);
    y += 15;
    drawMetricRow('Average Working Hours:', `${attendance.avgWorkingHours} hrs`, 0);
    drawMetricRow('Absent Count:', attendance.absentToday, 1);
    y += 24;

    // 4. Team Workload
    drawSectionHeader('4. Team Workload & Allocation');
    // Table Header
    doc.fillColor('#4B5563').fontSize(8);
    doc.text('MEMBER', 48, y);
    doc.text('ROLE', 170, y);
    doc.text('PROJECTS', 260, y);
    doc.text('ACTIVE TASKS', 330, y);
    doc.text('STATUS', 415, y);
    doc.text('WORKLOAD', 480, y);
    y += 12;
    doc.moveTo(40, y).lineTo(555, y).strokeColor('#E5E7EB').stroke();
    y += 6;

    for (const member of workload) {
      if (y > 750) {
        doc.addPage();
        y = 40;
      }
      doc.fillColor('#111827').fontSize(8.5).text(member.user.name, 48, y, { width: 115, ellipsis: true });
      doc.fillColor('#6B7280').fontSize(8).text(member.user.role.replace('_', ' '), 170, y);
      doc.fillColor('#111827').fontSize(8.5).text(String(member.assignedProjectCount), 275, y);
      doc.fillColor('#111827').fontSize(8.5).text(`${member.activeTasksCount} / ${member.totalTasksCount}`, 345, y);
      doc.fillColor(member.todayAttendanceStatus === 'PRESENT' ? '#059669' : '#D97706').fontSize(8).text(member.todayAttendanceStatus, 415, y);
      doc.fillColor(member.workloadLevel === 'OVERLOADED' ? '#DC2626' : member.workloadLevel === 'HIGH' ? '#D97706' : '#2563EB').fontSize(8).text(member.workloadLevel, 480, y);
      y += 16;
    }

    // Footer note
    if (y > 740) {
      doc.addPage();
      y = 40;
    }
    y += 15;
    doc.moveTo(40, y).lineTo(555, y).strokeColor('#E5E7EB').stroke();
    y += 8;
    doc.fillColor('#9CA3AF').fontSize(7.5).text('PlanForge Enterprise Project & Operations Management System - Confidential and Proprietary', 40, y, { align: 'center', width: 515 });

    doc.end();
  } catch (error: any) {
    console.error('Error generating PDF report:', error);
    if (!res.headersSent) {
      return res.status(500).json({ message: 'Failed to generate PDF report', error: error.message });
    }
  }
});
